### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by loadletter** [Sentaroh/SMBSync2#109] opened 2020-06-12 20:32 UTC
I have a task synchronizing to a Buffalo Linkstation NAS, last time I used it on version 2.24 it worked fine, now with version 2.29 It can't connect, which might be related to the smb library change.

![Screenshot_20200612-220826](https://user-images.githubusercontent.com/5257054/84543035-db57fe80-acfa-11ea-91fc-645b1b91b88c.jpg)

Sorry for the screenshot but I will try next week enabling logs.

**Comment by Sentaroh** [comment] 2020-06-13 04:10
Hi,

Could you please try SMB v2/3 (2.1.4)?
![図1](https://user-images.githubusercontent.com/4037866/84559764-8064ec80-ad78-11ea-8bee-597da360113b.png)


Best regards.
F.Hoshino

**Comment by loadletter** [comment] 2020-06-15 19:28
Thanks for you reply, but it prints the same error.

Apparently the NAS only supports SMBv1, setting SMBv1 works, but for some reason it was set to SMB 2/3 v2.12 since I don't remember ever changing configurations.

**Comment by Sentaroh** [comment] 2020-06-24 20:48
Here's a link to a version with modified SMB settings. Could you please test it?
https://drive.google.com/file/d/10nFItSnKmNFAESx7DSchQez5vYcsJVYI/view?usp=sharing

Best regards.

**Comment by PhilZ-cwm6** [comment] 2020-06-24 23:23
Why drop max SMB support to 3.0 in this case ? This will break enforced SMB 3.1 only servers
His NAS is SMB v1, which is not supported by SMB 2/3 (2.12) current min protocol
Maybe just auto-detect if SMB v1 to drop default to SMB V1 or lease SMB 2/3 (2.12) -> SMB 1/2/3 (2.12) and add min protocol 1.00

**Comment by Sentaroh** [comment] 2020-06-25 02:30
> His NAS is SMB v1

Sorry, I was disappointed.

> Why drop max SMB support to 3.0 in this case ?

When I tried to display the directory list with Windows7, NPE was generated, so I used SMB300.

> This will break enforced SMB 3.1 only servers

Updated:
SMB212 to use SMB300 so as not to affect current users.
SMB214 to use SMB311.

>  SMB 1/2/3 (2.12) and add min protocol 1.00

When jcifs-ng was adopted, the Min SMB Dialect was SMB1, but The error occurred frequently but could not be reproduced in my environment, so I was unable to determine the cause. As an alternative, I changed the Min SMB Dialect to SMB202.

Best regards.

**Comment by PhilZ-cwm6** [comment] 2020-06-25 06:40
If I am correct, windows 7 support is only smb 2.12. SMB 3.0 was introduced for win 8 and SMB 3.1 for win 10

Maybe on catch those errors, use message to suggest user downgrading protocol to match the server ?

**Comment by Sentaroh** [comment] 2020-06-25 07:28
> Maybe on catch those errors, use message to suggest user downgrading protocol to match the server ?

In jcifs-ng 2.1.3, if you use SMB311 in the Max SMB Dialect Incorrect results will result in exceptions such as NPE and IndexOutofBound. (This bug doesn't occur all the time, but only once every few times.)
This error is a bug in jcifs-ng 2.1.3 and will be fixed in jcifs-ng 2.1.4. It is.
If an error occurs in synchronous task editing, change the SMBv1 or SMBv2/3(2.14) Add a message to use.

Best regards.

**Comment by PhilZ-cwm6** [comment] 2020-06-25 11:40
sorry, just noticed 2.1.4 is still at SMB v3.1, so nothing broken

**Closed as completed** 2021-06-15 01:34 UTC
