### ISSUE TITLE
"Sync task ended successfully" notification cannot be dismissed on Android 11

### ISSUE THREAD

**Issue by acabtp** [Sentaroh/SMBSync2#218] opened 2021-01-30 13:12 UTC
The "Sync task ended successfully" notification cannot be swiped away or dismissed on Android 11.  Have to tap on it, which opens the app, to get it to go away.

**Comment by Sentaroh** [comment] 2021-01-30 22:02
Hi,

I tried with Pixel4A and Android Emulator, but could not reproduce the problem. Please let us know what kind of operation causes the problem.
The following is the operation in Emulator.
https://drive.google.com/file/d/12zlfFj7S8azmW9ONqbZKoLVN7ivXPf2e/view?usp=sharing

Best regards.

**Comment by acabtp** [comment] 2021-01-30 22:29
Hi, thanks for looking at this.   

Steps where I can reproduce issue:
Have a "Sync task ended successfully" notification from any SMBSync2 task, on a Samsung S10e with android 11 / oneui 3.0 with the 1/1/21 android security patch level (this is the latest available OTA software for the S10e).
Try to swipe notification away, are unable to.
This happens with both scheduled syncs and the StartSync widget.
It is listing SMBSync as an Alerting notification so the "Clear" option on the notifications drawer is disabled.

Expected behavior:
Notification can be dismissed, as you show happens properly in the emulator

I uploaded a video of the behavior I am seeing.  https://youtu.be/8-n7TRii-5g

Thanks again, please let me know if I can provide any further information or otherwise help.

**Comment by Sentaroh** [comment] 2021-02-01 01:21
Hi,

In the app, I have it set to onGoing(false), but for some reason it seems to be "On going notification".

Q1. Is the "Exit cleanly" option enabled? (Menu->Settings->Miscellaneous)
![image](https://user-images.githubusercontent.com/4037866/106404678-d822a600-6476-11eb-85ff-b6819f2c0bc1.png)

Q2. Is it an option in the system settings? Can you please be more specific?
>It is listing SMBSync as an Alerting notification so the "Clear" option on the notifications drawer is disabled.


Best regards.

**Comment by PhilZ-cwm6** [comment] 2021-02-07 20:17
I have no issues on A Galaxy S20 with latest Android 11 from Samsung without modifying any stock settings about the notifications
Let me know if you need more info on the possible settings

**Comment by PhilZ-cwm6** [comment] 2021-02-16 22:39
After latest Samsung update on the S20, Android 11, i also get the issue. But it is random, about 3 to 4/5 times. I found no option in SMBSync 2 or system notificatiin settings to fix it. Let me know if i can provide more info. Notifications from other apps still act normally

Best regards

**Comment by Sentaroh** [comment] 2021-02-17 01:49
Hi,

I've tried to do the Notice message in a separate process to isolate the problem, so could you please test it?
https://github.com/Sentaroh/SMBSync2/tree/2.48-1-fix-test-notice-message
-Eliminated Notice messages in separate processes.
-Separated the ID of the Notice message from the onGoing message.
-Notice message display is now done in a separate process. 

Best regards.

**Comment by PhilZ-cwm6** [comment] 2021-02-17 08:02
Thank you
Yes, now it can always be dismissed
However, we get two notifications, and the ongoing flashing notification persists some seconds after then sync end/start result notification. **This can be reproduced in the emulator using a long task and sending app to background during sync**.

I will wait for your next fix to test

Best regards

**Comment by Sentaroh** [comment] 2021-02-17 12:30
Hi,

It's fixed.(I tested : Pixel4a(SDK30), ZenFone5Z(SDK29), Huawei MediaPad M5(SDK28))
Could you please test it in your environment?
https://github.com/Sentaroh/SMBSync2/tree/2.48-1-fix-test-notice-message

Best regards.

**Comment by PhilZ-cwm6** [comment] 2021-02-17 20:13
Hi,
I tested on a Galaxy S20 latest Android 11 and Samsung updates. The problem is fixed, thank you.
I also tested on an Mi A1 with Android 9 and the emulator. It is properly working
Best regards

**Comment by Sentaroh** [comment] 2021-02-17 23:11
Hi,

Thank you.
Merged the changes into Branch2.48.

Best regards.

**Comment by PhilZ-cwm6** [comment] 2021-02-20 11:20
Hi,
After a scheduled task with two sync tasks, I get two success notifications:
- One global Success notification
- One about success of the last sync task

This is on a Galaxy S7 with Android 8.0. I did not have time to test more and I won't have access to the emulator in the next days
However, it is hard to reproduce as it doesn't happen everytime
Best regards

**Comment by Sentaroh** [comment] 2021-02-21 01:24
Hi,

The following changes have been made.
https://github.com/Sentaroh/SMBSync2/tree/2.49-1-fix-notification
- In Android 28 and later, changed from startService() to startForegroundService()
- On Android 28 or later, change from stopForeground(false) to stopForeground(Service.STOP_FOREGROUND_DETACH)

I was not able to reproduce the error in my environment, could you please test it?

Best regards.

**Comment by PhilZ-cwm6** [comment] 2021-02-21 20:44
I am away until next week, will test and report later
Thank you and best regards

**Comment by PhilZ-cwm6** [comment] 2021-03-04 15:50
Hi,
I could not test the latest changes.
However, here are pics of the bug I could catch on the previous 2.49 version, since I did not yet update:
![20210303_102934](https://user-images.githubusercontent.com/2428217/109989722-0eb73f00-7d09-11eb-8d4b-f9ab601763b6.jpg)

This time it was on a Poco X3 with MIUI and Android 10. The icon was once flashing and once not. I include a video with it flashing despite it was done
https://youtu.be/KpXn_h3vYj4

The task was started manually, not by schedule. Pressed Home button and turned off screen until task is completed. I could reproduce 2 times, but not always

I will test asap the latests changes. However, since the problem occurs also on Android 10 and your changes were to fix for Android 8, I doubt it is fixed

Best regards

EDIT: I noticed more changes were done than enabling the method for Android 8 and before. I will test and let you know if I can reproduce it again. In any case, I hope the pic/vid can help you to validate your fixes
Best regards

**Comment by PhilZ-cwm6** [comment] 2021-03-04 21:13
Ok, after further testing with latest changes, I could not get the double notification to persist
I can see that the task end notification is issued in the Notification log activity, but it doesn't persist in the display

I will report if I notice any anomaly in the various devices

Thank you and best regards

**Comment by Sentaroh** [comment] 2021-03-07 05:58
Hi,

Please try Ver2.51.

Best regards.

**Comment by PhilZ-cwm6** [comment] 2021-03-07 14:24
Hi,
I tested The latest version in emulator API 30, Galaxy S20 API 30, Poco X3 NFC API 29, Galaxy S7 API 27 and Galaxy Note 4 API 23
Both with manual sync (1 or 2 tasks) and by manual schedule start, sending app to background or exiting it
No issues noticed

Thank you and best regards

**Closed as completed** 2021-06-15 12:44 UTC
